### ISSUE TITLE
Add panel height option

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#14]
To make it more flexible, would be good to add a `$panel-height` option in the settings. Default value could be `100%`, but easy access to change when sites need a full screen menu of `100vh` or something.

**Comment by mattada** [comment]
Correct my if I'm wrong, but currently the panel  height fits / expands to the content right? There are few cases this has played out where we need it to be 100vh, or any set height.

**Comment by erwstout** [comment]
Yes, it fits the content/height of the nav items, any other time i've only done `100vh`.
