### ISSUE TITLE
Why rely on jQuery for panel animation?

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#15]
The panel reveal currently uses the jQuery `slideToggle()` method, but why not use CSS animations/transitions which are faster and more performant than JS for this? Also, to my knowledge, this only allows something to slide up or down, not left or right. Using CSS would open up the possibility to the panel to be revealed in any number of ways.

**Comment by erwstout** [comment]
This stems from what and why we created Nifty Nav. We were using a different tool for mobile menus, and it was causing lots of issues (one of which was off canvas left/right and scrolling issues) so when we built it - we only wanted it to come down from the top and not side to side as far as jQuery, thats what made sense at the time.

**Comment by mattada** [comment]
Just for reference. THIS site was the reason Nifty Nav was born. 
http://www.fastrackids.com/

We had a jquery function in place for an alert bar, and we hijacked it to hold a menu. Its grown up a bit, but its roots were in a jquery toggle alert bar.

**Comment by erwstout** [comment]
That and that old BigSlide jQuery plugin is what it replaced.
