### ISSUE TITLE
Update CSS for header

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#16]
Currently Nifty Nav uses this code
```
header{
  z-index: $header-index;
}
```

but this should probably be namespaced in some way. In its current state, it is applying this z-index to any header in the site, and this can potentially cause unexpected issues in other areas, for example any `header` that may be placed inside on an `article`, `main`, etc.

**Comment by erwstout** [comment]
I agree this should be adjusted.

**Comment by erwstout** [comment]
This was changed in release 3.0.0
