### ISSUE TITLE
Plans to make Nifty Nav a true jQuery function?

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#17]
In its current state Nifty Nav is a function that relies on jQuery. It works so no issue there, but why not just make it a true jQuery function so you can choose what element is will act upon? Example `$(item).niftyNav();`

For our sites there is usually one sliding menu, but if there is ever a design that needs more than one the current implementation no longer works, as all menus will have the exact same properties.

A true jQuery plugin set up will allow for more than one menu/panel, and will also allow for situations when someone wants to chain additional jQuery methods to the Nifty Nav. Example `niftyNav().css('color', 'red');` would cause an error while `$(item).niftyNav().css('color', 'red');` will work fine.

**Comment by erwstout** [comment]
There are no plans to change this at the moment, but it just goes back to where we were at the time and how it was built then. I don't feel any certain way about this, as I can see why it would be an enhancement. On the other hand, we use it on 99% of our sites and I've never encountered that need. I think it would really come down to if @mattada would want to allocate time to change this.

**Comment by mattada** [comment]
I see @bebaps point about making this more stand alone and supporting multiple elements. We havent seen it yet in our work but I have seen designs with a left and right off canvas menu structure. Not saying anything about it being a good idea, but could happen. 

Im okay with continued dev on this if it helps our work. If we spend a dozen hours on this, and in the end nothing is different for the next project, then is it worth it?

**Comment by bebaps** [comment]
Continuation on this:

Today @erwstout got an error that "$ is not a function" when using Nifty Nav. Inspecting it showed:

![screen shot 2017-03-31 at 11 19 14 am](https://cloud.githubusercontent.com/assets/5995907/24563730/5221f246-1604-11e7-836d-e08a183a3c9d.png)

The line before Nifty Nav was defined is where the jQuery no-conflict wrapper was closed, and as such after that WordPress does not know what `$` means. This was not an issue when Prelude was registering its own version of jQuery, but since that has been removed we need to be aware of this.

Nifty Nav now must be wrapped in a no-conflict wrapper to work properly (the plugin itself, not just the function call). We will need to make updates anyway, and I still believe making this a true jQuery plugin is still a valid option. That way, it can only ever function on a true jQuery object to begin with.

As to @mattada last comment I think it is worth it to make the enhancements but it would be like a code in free time type of thing. True we have not really coded these types of navs in our work, but that is just because our designer or Rule29 has only ever been designing the same type of nav patterns, so it is up to their imaginations on when that will change.

**Comment by erwstout** [comment]
This is now an actual jQuery function. Example usage:

```js
$('#nifty-nav-toggle').niftyNav();
```
