### ISSUE TITLE
Add default sub-menu styling

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#18]
Currently there is no default styling for submenus. Currently with this code

```
niftyNav({
  subMenus: true,
});
```

the submenus still display on the page, and clicking the parent hides them.

CSS should be added to hide them with `display: none` by default.

Also, if this option is set to `true` it would be good to add a default icon or something to visualize that there is a sub menu available.

**Comment by erwstout** [comment]
Agree on the default hiding of the submenus, as for the icon, etc... I think thats treading too close to the design aspect and it should be more open ended and case by case depending on the design supplied. 

One thing to note on that, is Nifty Nav wasn't ever intended to be an out of the box up and running solution, but a core starting point for our navigation systems - so we should always expect/plan for a little bit of time dialing in the design.

**Comment by mattada** [comment]
I agree the display:none should be the scss default

I also agree that no, there should not be a default icon for a submenu toggle.
