### ISSUE TITLE
Add support for button text

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#20]
Currently, the toggle button assumes that it will always be a hamburger icon, and adding text alongside of the hamburger icon requires basically a custom implementation in order to keep the icon and text in the same element.

This should probably be updated to easily allow text to be shown alongside the hamburger icon.

**Comment by erwstout** [comment]
Yeah I can go either way on this. We don't use that pairing often so I haven't ran into it much, but I can see the potential benefits. More of a finding time to implement thing.

**Comment by erwstout** [comment]
Closing this issue as this will soon be unmaintained.
