### ISSUE TITLE
Update Example

### ISSUE THREAD

**Issue by erwstout** [factor1/nifty-nav#5]

**Comment by erwstout** [comment]
Need a better example, and should probably be on brand... I know its probably on the list as part of the marketing push. @mattada

**Comment by erwstout** [comment]
Any update on branding for this? @mattada

**Comment by mattada** [comment]
On the new f1 site we have it featured like so. Im sure we can have allison design a pretty example site for us. 

![screen shot 2016-05-12 at 9 05 47 am](https://cloud.githubusercontent.com/assets/10223806/15221574/d92eb644-1820-11e6-993b-c14941853854.png)

**Comment by erwstout** [comment]
@mattada any interest in doing this still or should we drop this from the package?

**Comment by mattada** [comment]
We can drop it.
