### ISSUE TITLE
subMenuParentLink

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#9]
This option is on by default, but is preventing the parent nav items from being followed in a standard dropdown implementation. It is targeting all parent links on the page instead of being isolated to just those inside of nifty nav itself.

```
if( subMenuParentLink === false ){
      $('.menu-item-has-children > a').click(function(event){
        event.preventDefault();
      });
    }
```

should be more like 

```
if( subMenuParentLink === false ){
      $('.nifty-panel .menu-item-has-children > a').click(function(event){
        event.preventDefault();
      });
    }
```

**Comment by erwstout** [comment]
Fixed in release [2.1.4](https://github.com/factor1/nifty-nav/releases/tag/2.1.4)
